### ISSUE TITLE
DOAWaitCondition Timeout - DOA CloudFormation Stack Failures 

### ISSUE THREAD

**Issue by ckalandar** [Accenture/adop-doa-materials#19]
DOA CloudFormation Stack Failures

**Comment by SachinKSingh28** [comment]
@ckalandar : could you please provide more information from the EC2 instance? It must have failed because one of the cloud init command failed but until we have that information we can't troubleshoot further. 

**Note** : Please remove any credentials or IP addresses from the cloud-init logs.
