### ISSUE TITLE
Updating Instance Type from m1 to m3

### ISSUE THREAD

**Issue by uptownaravi** [Accenture/adop-doa-materials#23]
m3 upgraded instance types are available which are of less cost than m1 instances.

request to modify the json file with the latest m3 instance type.

template to be updated is available at https://github.com/Accenture/adop-doa-materials/blob/master/Lab_Modules/Module_7/Tomcat_7.json

**Comment by dsingh07** [comment]
Hi @uptownaravi 

Thank you for your suggestion!

Would it possible for you to make a pull request for this?

Thanks,
Dharmanshu

**Comment by uptownaravi** [comment]
Commit https://github.com/Accenture/adop-doa-materials/commit/81106f5be2ea4d90a96e1e41a21c539b490a0216

has fixed the instance type issue ( changed to t2.medium). Closing this issue as resolved.
