### ISSUE TITLE
Need to replace Jmeter wget with new path in Module3_FOSS_Java_Manual - Reference_Application_Performance_Tests job

### ISSUE THREAD

**Issue by uptownaravi** [Accenture/adop-doa-materials#25]
In the jenkins job Reference_Application_Performance_Tests under Module3_FOSS_Java_Manual / Java_Reference_Application path to the Jmeter library needs to be changed as below
Jmeter is currently at 3.3 as per http://jmeter.apache.org/download_jmeter.cgi
and the 2.13 which is used in our jobs are moved to archives https://archive.apache.org/dist/jmeter/binaries/

wget http://www.apache.org/dist/jmeter/binaries/apache-jmeter-2.13.tgz
to
wget http://archive.apache.org/dist/jmeter/binaries/apache-jmeter-2.13.tgz

**Comment by uptownaravi** [comment]
Hi Sachin

After checking this, could see that the fix should be in the groovy script present in https://github.com/Accenture/adop-cartridge-doa-m3/blob/master/jenkins/jobs/dsl/java_reference_application_jobs.groovy

There already exits a pull request which has the necessary modification 
https://github.com/Accenture/adop-cartridge-doa-m3/pull/1

Could you please review that and merge.

**Comment by RobertNorthard** [comment]
Thanks @uptownaravi this has now been merged.
