### ISSUE TITLE
DevOps Academy: Critical failure at Chef build

### ISSUE THREAD

**Issue by Gemelli23** [Accenture/adop-doa-materials#26]
When you follow the instructions for the start of day 2 to set up the Chef server on your AWS instance, the installation fails with the following text:

+ echo 'Adding EC2 instance to NGINX config using xip.io...'
Adding EC2 instance to NGINX config using xip.io...
+ export SERVICE_NAME=EC2-Service-Extension-1
+ SERVICE_NAME=EC2-Service-Extension-1
+ cp /workspace/Platform_Management/Load_Platform_Extension/service/aws/ec2-extension.conf ec2-extension.conf
+ sed -i s/###EC2_SERVICE_NAME###/EC2-Service-Extension-1/ ec2-extension.conf
+ sed -i s/###EC2_HOST_IP###/10.0.1.227/ ec2-extension.conf
+ docker cp ec2-extension.conf proxy:/etc/nginx/sites-enabled/EC2-Service-Extension-1.conf
+ docker exec proxy /usr/sbin/nginx -s reload
nginx: [emerg] BIO_new_file("/etc/nginx/ssl/cert.crt") failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/nginx/ssl/cert.crt','r') error:2006D080:BIO routines:BIO_new_file:no such file)
Build step 'Execute shell' marked build as failure
[ssh-agent] Stopped.
Finished: FAILURE

This has been verified by multiple users.

**Comment by RobertNorthard** [comment]
Closing issue as this has been resolved in PR https://github.com/Accenture/adop-doa-materials/pull/27. This issue was due to unused SSL certs being removed from adop-nginx in https://github.com/Accenture/adop-docker-compose/commit/bc5b9d18dfaef6b934b59d607a2deafcfc1074b9
